#!/usr/bin/perl
use warnings;
use strict;

my $file = shift @ARGV;
my $output_ratio   = shift @ARGV;
my $quiet = shift || 1;
my $output_counter = 0;
my $input_counter  = 0;

my $downsample_averaging = 0;

my $downsample_samples     = 0;
my $downsample_accumulator = 0;

resample ($file, $output_ratio);

sub resample {
	my $file = shift;
	my $output_ratio = shift;
	open(FILE, '<', $file);


while ( my $line = <FILE> ) {
    $line =~ s/\#.*$//g;
    $line =~ s/[^01]//g;

    for my $digit ( split( //, $line ) ) {
        $input_counter++;
        if ( $output_ratio > 1 ) {
            while ( $output_counter < ( $input_counter * $output_ratio ) ) {
                $output_counter++;
                print $digit;
		print
                   " # Input sample $input_counter. Output sample: "
                  . $input_counter * $output_ratio . " - "
                  . $output_counter . "\n" if (!$quiet) ;

            }

        }
        else {

            if ($downsample_averaging) {
                $downsample_samples++;
                $downsample_accumulator += $digit;
                if ( ( $input_counter * $output_ratio ) >=
                    ( $output_counter + 1 ) )
                {
                    $output_counter++;
                    print STDOUT (
                        ( $downsample_accumulator / $downsample_samples ) > 0.5
                        ? '1'
                        : '0' );

		print 
                       " # Input sample $input_counter. ($digit ) Output sample: "
                      . $input_counter * $output_ratio . " - "
                      . $output_counter . "\n" if (!$quiet);
                    $downsample_samples     = 0;
                    $downsample_accumulator = 0;
                }
                else {
                    print STDERR
                      "  # Input sample $input_counter Output sample "
                      . $input_counter * $output_ratio
                      . " DISCARDED\n" if (!$quiet);

                }

            }
            else {

                if ( ( $input_counter * $output_ratio ) >
                    ( $output_counter + 1 ) )
                {
                    $output_counter++;
                    print $digit;
		    print
                       " # Input sample $input_counter. Output sample: "
                      . $input_counter * $output_ratio . " - "
                      . $output_counter . "\n" if (!$quiet)
                }
                else {
                    print STDERR
                      "  # Input sample $input_counter Output sample "
                      . $input_counter * $output_ratio
                      . " DISCARDED\n" if (!$quiet);
                }
            }

        }

    }

}

close(FILE);
print "\n";
};
