#!/bin/bash

KEYBOARD=$1
KEY=$2
BASE_FILENAME="testcases/$KEYBOARD/key-$KEY-"

for count in 1 5 10 
do

	for press_speed in slow fast
	do

		FILE="$BASE_FILENAME-$count-presses-$press_speed"
		RAWFILE="$FILE.raw"
		OUTFILE="$FILE.data"
		if [ -f $OUTFILE ]; then
			mv $OUTFILE "$OUTFILE.bak"
		fi
		echo "Ready to capture $FILE"
		read 
		sigrok-cli --config samplerate="16M" --driver=saleae-logic16 --samples=150M -C 14,15 -O csv -T invert |cut -d , -f 2,3 > $RAWFILE
		
		echo "#SAMPLES-PER-SECOND: 2000" >> $OUTFILE
		echo "#TITLE: $FILE" >> $OUTFILE
		echo "#PRESSES: $count" >> $OUTFILE
		
		uniq $RAWFILE |perl -p -0 -e's/1,1[\r\n]+0,1/1,1/msg; s/1,1[\n\r]+0,1/1,1/gsm; s/1,0[\r\n]+1,1/1,1/gms '  |grep ^1| cut -d , -f 2 | grep -P '\d+' >> $OUTFILE
		
		uniq -c $OUTFILE
	done
done
