#!/bin/bash

KEYBOARD=$1
KEY=$2
BASE_FILENAME="testcases/$KEYBOARD/key-$KEY-"

mkdir -p "testcases/$KEYBOARD"

for count in 1 5 10 
#for count in 10 
do


	for press_speed in slow fast
	#for press_speed in fast
	do


		if [ $press_speed == 'fast' ]; then
			time_multiplier=15
		else
			time_multiplier=22

		fi
		capture_time=$(($count * $time_multiplier))
		FILE="$BASE_FILENAME-$count-presses-$press_speed"
		RAWFILE="$FILE.raw"
		OUTFILE="$FILE.data"
		if [ -f $OUTFILE ]; then
			mv $OUTFILE "$OUTFILE.bak"
		fi
		echo "Ready to capture $FILE"
		read 
		sigrok-cli --config samplerate="16M" --driver=saleae-logic16 --samples=${capture_time}M -C 14,15 -O csv -T invert |cut -d , -f 2,3 > $RAWFILE
		
		echo "#SAMPLES-PER-SECOND: 2000" >> $OUTFILE
		echo "#TITLE: $FILE" >> $OUTFILE
		echo "#PRESSES: $count" >> $OUTFILE
		
	
	uniq $RAWFILE |  perl -p -0 -e's/1,0[\r\n]+1,1/1,1/msg; #slow turn on  \
		 s/1,1[\r\n]+1,0/1,1/msg; # fast turn off \
		 s/0,0[\r\n]+0,1/0,0/gsm; # ?? \
		 s/0,1[\n\r]+0,0/0,0/gsm; #slow turn off  ' |uniq |grep ^1 |cut -d, -f 2|grep -P '\d+' >> $OUTFILE
		uniq -c $OUTFILE
		./reformat_keypress_data $OUTFILE
	done
done
