// generated by gen_map.py
#pragma once
#include <avr/pgmspace.h>
#define XXX 0xFF
PROGMEM const uint8_t led_LUT[2][128] = {
   {
        XXX, XXX, 144, 177, 150, 153, XXX,   0,   3,   6,   9,  12,  15,  18, 123, 120, 
        XXX, XXX, 145, 178, 151, 154, XXX,   1,   4,   7,  10,  13,  16,  19, 124, 121, 
        XXX, XXX, 146, 179, 152, 155, XXX,   2,   5,   8,  11,  14,  17,  20, 125, 122, 
        138, 141, 159, XXX, XXX, XXX, 171, 117, 114, 111,  21,  24,  27,  30,  33,  36, 
        139, 142, 160, XXX, XXX, XXX, 172, 118, 115, 112,  22,  25,  28,  31,  34,  37, 
        140, 143, 161, XXX, XXX, XXX, 173, 119, 116, 113,  23,  26,  29,  32,  35,  38, 
        156, 174, 162, 147, 165, 168, XXX, XXX, 126, 108,  39,  42,  45,  48,  51,  54, 
        157, 175, 163, 148, 166, 169, XXX, XXX, 127, 109,  40,  43,  46,  49,  52,  55, 
    },
    {
        158, 176, 164, 149, 167, 170, XXX, XXX, 128, 110,  41,  44,  47,  50,  53,  56, 
        129, 105,  57,  60,  63,  66,  69,  72, 132, XXX, XXX, 102,  75,  78,  81,  84, 
        130, 106,  58,  61,  64,  67,  70,  73, 133, XXX, XXX, 103,  76,  79,  82,  85, 
        131, 107,  59,  62,  65,  68,  71,  74, 134, XXX, XXX, 104,  77,  80,  83,  86, 
         87, 135,  99, XXX, XXX, XXX, XXX, XXX,  96,  93,  90, XXX, XXX, XXX, XXX, XXX, 
         88, 136, 100, XXX, XXX, XXX, XXX, XXX,  97,  94,  91, XXX, XXX, XXX, XXX, XXX, 
         89, 137, 101, XXX, XXX, XXX, XXX, XXX,  98,  95,  92, XXX, XXX, XXX, XXX, XXX, 
        XXX, XXX, XXX, XXX, XXX, XXX, XXX, XXX, XXX, XXX, XXX, XXX, XXX, XXX, XXX, XXX, 
    }
};
